
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-organic-s24-5pm-3
owner: ucsb-cs156-s24
repo_name: proj-organic-s24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBXy3rA","is_bot":false,"login":"andrew-kwon1","name":""},"headRefName":"ak-coursestaffpageplaceholder","number":42,"title":"CRUD STAFF OPERATION Go to Staff Page from Course Page","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/pull/42"},{"author":{"id":"U_kgDOBXuyEw","is_bot":false,"login":"30912hyl","name":""},"headRefName":"aaron-edit2","number":36,"title":"added school edit pages, utils, tests, stories","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/pull/36"},{"author":{"id":"MDQ6VXNlcjQzNzgzODc3","is_bot":false,"login":"yuxiaolejs","name":"Unics Yu"},"headRefName":"Tianle-CommitMSG","number":35,"title":"[feat] Expose git info msg","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/pull/35"},{"author":{"id":"MDQ6VXNlcjQ5Nzc0NzYx","is_bot":false,"login":"Xalex217","name":""},"headRefName":"aaron-endButton","number":34,"title":"Created Delete button on Delete schools page","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/pull/34"},{"author":{"id":"U_kgDOBXuyEw","is_bot":false,"login":"30912hyl","name":""},"headRefName":"30912hyl-dev","number":32,"title":"Added information about the app on the Home Page and tests","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/pull/32"},{"author":{"id":"MDQ6VXNlcjQzNzgzODc3","is_bot":false,"login":"yuxiaolejs","name":"Unics Yu"},"headRefName":"Tianle-GHA-b01","number":23,"title":"[feat] GitHub App integration","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/pull/23"}]
