
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-organic-s24-5pm-3
owner: ucsb-cs156-s24
repo_name: proj-organic-s24-5pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ5Nzc0NzYx","is_bot":false,"login":"Xalex217","name":""},"headRefName":"AaronR-TylerTSchoolCreate","number":73,"title":"Aaron r tyler t school create","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/pull/73"},{"author":{"id":"MDQ6VXNlcjQzNzgzODc3","is_bot":false,"login":"yuxiaolejs","name":"Unics Yu"},"headRefName":"Tianle-SanityCheck","number":72,"title":"[feat] Sanity Check before the app starts","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/pull/72"},{"author":{"id":"U_kgDOBtxm2A","is_bot":false,"login":"sherpatran","name":""},"headRefName":"TylerT-SchoolCreateButtonNew","number":70,"title":"Linked API to Create School button, added tests and Storybook v.2","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/pull/70"},{"author":{"id":"U_kgDOBXy3rA","is_bot":false,"login":"andrew-kwon1","name":""},"headRefName":"ak-staffcrud","number":67,"title":"Staff page staff list and add staff","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/pull/67"},{"author":{"id":"MDQ6VXNlcjQzNzgzODc3","is_bot":false,"login":"yuxiaolejs","name":"Unics Yu"},"headRefName":"Tianle-deployScript","number":62,"title":"[tool] A tool for configuring dokku app quickly","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/pull/62"},{"author":{"id":"MDQ6VXNlcjQzNzgzODc3","is_bot":false,"login":"yuxiaolejs","name":"Unics Yu"},"headRefName":"Tianle-GHA-com.tianleyu.github","number":46,"title":"[reopen][feat] GitHub App integration #23","url":"https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-3/pull/46"}]
